name: shofri
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.12+2
  page_indicator: ^0.3.0
  image_picker: ^0.6.7+11
  flutter_svg: ^0.19.0
  provider: ^4.3.2+1
  path_provider: ^1.6.14
  toast: ^0.1.5
  badges: ^1.1.1
  qr_code_scanner: ^0.0.13
  permission_handler: ^5.0.1+1
  google_maps_flutter: ^0.5.30
  geolocator: ^6.0.0+1
  geocoder: ^0.2.1
  google_maps_webservice: ^0.0.18
  flutter_google_places: ^0.2.6
  modal_bottom_sheet: ^0.2.0+1
  shared_preferences: ^0.5.10
  location: ^3.0.2
  dio: ^3.0.10
  countdown_flutter: ^0.1.2
  charts_flutter: ^0.9.0
  qr_flutter: ^3.2.0
  file_picker: ^1.13.3
  upgrader: ^2.6.0
  json_annotation: ^3.0.1
  font_awesome_flutter: ^8.8.1
  firebase_auth: 
  firebase_core: 
  cloud_firestore:
  fluttertoast: ^7.0.4
  google_sign_in: ^4.5.4
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/shofri-intro.mp4
    - assets/scanqr.png
    - assets/chatwithseller.png
    - assets/offlinetoonline.png
    - assets/followshop.png
    - assets/circle.png
    - assets/round.svg
    - assets/dashed-circle.png
    - assets/shoplogo.png
    - assets/non_verified.png
    - assets/home-wallpaper.png
    - assets/seller-profile-wallpaper.png
    - assets/public-shop-wallpaper.png
    - assets/summer-wallpaper.png
    - assets/dress.png
    - assets/jacket.png
    - assets/backpack.png
    - assets/shop-settings-wallpaper.png
    - assets/profile-wallpaper.png
    - assets/shop-settings.png
    - assets/qr-code.png
    - assets/money-withdraw.png
    - assets/sad.png
    - assets/coins.png
    - assets/money.png
    - assets/shopping-cart.png
    - assets/shopping-cart.svg
    - assets/add-order.png
    - assets/order.png
    - assets/qr-code-wallpaper.png
    - assets/following.png
    - assets/photo.png
    - assets/photo2.png
    - assets/men1.png
    - assets/men2.png
    - assets/men3.png
    - assets/men4.png
    - assets/image8.png
    - assets/women.png
    - assets/chanel.png
    - assets/linechart.png
    - assets/scarf.png
    - assets/womenshoe.png
    - assets/details.png
    - assets/icon.png
    - assets/chat.png
    - assets/profile.png
    - assets/scanner.png
    - assets/idcard.png
    - assets/selfi.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
